# IAIMKn0w:s0c.ls crE8d by PipStuart <Pip@CPAN.Org> to mirror l8st s0cial-media (Twitter && FaceBook) connection details since bans && censorship both worsen;
# 2du:upd8 Twtr folOerz wi comNtz of description blurbz, expand name stringz wi elipses (&& Unicodez)?; n0t:initially omiting redundant duplic8d +both folOng;
# n0t:d8:IAI when crE8d 1st I initE8d reciprocal folOng of all piped below who folOd me before just 1-sidedly (since I might benefit knowing more about them);
# 2du:rEordr && mAB grup c@egorEz proly by prIoriT,number each sub,visit about pAgez 2 hRvSt valUd DtAlz,EvN2aly alsO mirror my 75 twEtz,11 listz,1953 lIkez?;
# 2du:J54MAS0C:Bep=(714)724-0491,Kyle=(920)903-6810,MikeHeckner=(920)460-8577,LynnGabbay=(646)306-8987, Maga=(920)378-4013,KarenIversonRiggers=(920)527-0810 ;
U2b :Joind8  NormalName                 .Com/user/       e-mail                  #   Links
  96Q "Turd Flinging Monkey"          MorgueToeTag    "Morgue33@GMail.Com"       # HTTPS://BitChute.Com/channel/turdflingingmonkey
                        # HTTPS://Twitter.Com/TFMonkeyYouTube                    # HTTPS://Shop.SpreadShirt.Com/TurdFlingingMonkey
                        #             PayPal:'TFMonkey' crazy long gNr8d link    # HTTPS://Patreon.Com/turdflingingmonkey  ## mABl8radd Celestina's Instagram
  DAU "Sandman"                       SandmanMGTOW                               #         BitChute, Minds, Gab.AI, Twitter, FaceBook, PayPal, Patreon
  FBC "TheQuartering"                                 "?@?.Com"                  # Twitch,           Minds,         Twitter, FaceBook
  B29 "Owen Benjamin"                 owenbenjamincomedy                         # WebSite,                         Twitter, FaceBook,              Instagram
      "Monstercat: Uncaged"
      "Timcast"
      "Tim Pool"
      "Omegon"
      "Philip DeFranco"
      "Jordan B Peterson"
      "PewDiePie"
      "The Rubin Report"
      "Liana K"
      "Lauren Chen"
      "Sam Harris"
      "MDZ jimmY"
      "Armoured Skeptic"
      "PhilosophyInsights"
      "Rationality Rules"
      "Anna Akana"
      "Computerphile"
      "Matt Dillahunty"
      "Just Write"
      "Jonathan Pageau"
      "Wisecrack"
      "DeadAceBS"
      "Counter Arguments"
      "CosmicSkeptic"
      "Think Club"
      "Lindsay Shepherd"
      "ashtonbirdie"
      "Miss Misa"
      "Shoe & Skeptic"
      "ContraPoints"
      "Bret Weinstein"
      "Genetically Modified Skeptic"
      "Casually Explained"
      "Creationist Cat"
      "Ozzy Man Reviews"
      "Kurzgesagt - In a Nutshell"
      "Enlightainment"
      "Shoe0nHead"
      "Eric Weinstein"
      "agadmator's Chess Channel"
      "ObsidiaMedia"
      "ChessNetwork"
      "Ozzy Man & Mozza Catch Up"
      "lacigreen"
      "ManOfAllCreation"
      "Chess.com"
      "Cassie Jaye"
      "Ranting Monkey"
      "TL;DR"
      "Wizard Of Cause"
      "AronRa"
      "Numberphile"
      "Chris Ray Gun"
      "Foundation for Economic Education"
      "Alexander Grace"
      "BRIGHT SIDE"
      "Thoughty2"
      "Internet Comment Etiquette with Erik"
      "The Atheist Experience"
      "Essential Truth"
      "Jeff Holiday"
      "John Cedars"
      "TED"
      "AntiCitizenX"
      "GQ"
      "Life Noggin"
      "Turtle Juice"
      "Viced Rhino"
      "Marcel Enlightened"
      "21 Studios"
      "Owen Benjamin"
      "Drunken Uncle"
      "Censored Gaming"
      "VesperArcade"
      "OpenAI"
      "Brendan O'Neill Archive"
      "Jonathan Blow"
      "standupmaths"
      "Screeps"
      "Pop Culture Detective"
      "Angry Foreigner"
      "AwakenWithJP"
      "TheGamerFromMars"
      "Rachaellust"
      "Tree Of Logic"
      "Trap Nation"
      "Reloaded Insight"
      "Paul VanderKlay"
      "Jordan Peterson Fan Channel"
      "CGP Grey"
      "Dose of Truth"
      "Arthur Arcturus"
      "Just a Robot"
      "RammsteinTheBand"
      "Cats - Topic"
      "REACT"
      "ItsSkyLOL"
      "Extra Credits"
      "realityDUBSTEP"
      "OnlyChillstep"
      "Clash of Ideas"
      "JaclynGlenn"
      "The White House"
      "Lauren Southern"
      "Neel Kolhatkar"
      "Vox"
      "Dr. Debra W Soh"
      "AsapSCIENCE"
      "Innuendo Studios"
      "Neel TV"
      "DubStation"
      "Aphenda"
      "The Game Theorists"
      "No Safe Spaces Movie"
      "Sorting Myself Out"
      "Smosh"
      "The Film Theorists"
      "Crysta Cat"
      "Troy Leavitt"
      "Ramble"
      "50 Stars"
      "Shoryuken"
      "Nerdwriter1"
      "The Conservative Station"
      "TRUTHBOMBS"
      "Immortal Mindz"
      "ProcrastiTara"
      "Christopher Hitchens - Topic"
      "ThyNameIsSkeppy"
      "Armoured Gregory"
      "Thom Avella"
      "GameHut"
      "anarchopac"
      "Sandman 2"
      "TrueUnderDawgGaming"
      "ScienceNET"
      "Cuck Philosophy"
      "The Prim Reaper"
      "Badger Live Streams"
      "Pangburn Philosophy"
      "Ella Grant"
      "Colin's Last Stand: Side Quest"
      "Bite-sized Philosophy"
      "The Dave Cullen Show"
      "Street Fighter V - Topic"
      "Mythicist Milwaukee"
      "HypnosMirror"
      "ERB"
      "Godless Cranium"
      "The Matrix - Topic"
      "Seeker"
      "Mouthy Buddha"
      "ZeroFox Given"
      "YouTuber Law"
      "BarackObamadotcom"
      "Going Quantum"
      "Beyonce"
      "JennaMarbles"
      "Bad Lip Reading"
      "Adam Shomsky"
      "HMtv"
      "FBE"
      "Invisible Children"
      "Henrich Winside Achberger"
      "EDMLyrics"
      "ForeverChill"
      "Vital EDM"
      "DjEphixa"
      "ElectroHouseMusic010"
      "Simon's Cat"
      "Charisma on Command"
      "Candace Owens"
      "UltraDavid"
      "HighImpactFlix"
      "Bloggingheads.tv"
      "Dr. Layman"
      "Crypto Cred"
      "Mother Jones"
      "Salty Circus"
      "Bettina Arndt"
      "Canadian Association for Equality"
      "desk"
      "hbomberguy"
      "Armoured Media"
      "OMG! UBUNTU!"
      "boratFAN999"
      "Mobile Mgtow"
      "Steven Pinker - Topic"
      "Satsu2Cents"
      "Freedom in Thought"
      "Vernaculis"
      "The Future Is Now"
      "New Thinking Allowed with Jeffrey Mishlove"
      "RedHeadRedemption"
      "feministfrequency"
      "Huggy"
      "Shannon Q"
      "John Ward"
      "Joshua Hutchison"
      "Unbelievable?"
      "Dangerfield"
      "Declan Black"
      "DeflatingAtheism"
      "Super Eyepatch Wolf"
      "Rational Philosophy"
      "Christina Hoff Sommers"
      "Pyrocynical"
      "ContraPointsLive"
      "bar bar"
      "Kittens - Topic"
      "th_pion"
      "beppu"
      "Donald Glover"
      "Soulcalibur - Topic"
      "The Here and How Podcast"
      "For Britain"
      "Real Time with Bill Maher"
      "Paul Elam"
      "Skrillex"
      "Lauren Rose"
      "Matt Christiansen";
Twtr: @PipStuart8       "Pip Stuart" Born:Dec.13 1976     # GNU/Linux Perl game developer. Don't like ideologies or identity politics. Skeptical of anything
    Loc8d:Oshkosh, Wisconsin, U.S.A  Joined:June 2015     #   seeming dogmatic. Open-minds and empathy are my preference.
b   Followers: ('^' caret=authentic8d_blue_check-mark_user, '%' percent=locked_account, '|' pipe=only_following_them, '+' plus=them_also_following__me__back)
 0^ + @larrykim         "Larry Kim" # CEO @MobileMonkey_, Founder @WordStream (acquired for $150M) Columnist @Inc,@Medium,@CNBC. Startups,AdWords,Chatbots....
 1  + @PsychologyDoc    "Psychology Philosophu..." (fancy Unicode && Emoji used)
 2  + @k8iekat          "Kathryn I. Wallace"              # I'm just here by the same cosmic occurence as yourself...
 3  + @subohmcircus     "Super Miserabilis prorsus e..."
 4  + @Greyling_PJ      "PJ Greyling"
 5  + @NoahSGeller      "Noah Geller"
 6  + @jefftystep       "J. Tyler Stephenson"
 7  + @rigolgm          "Sprint The Plank"
 8  + @jpace13          "Jeff Pace"
 9  + @kemper51         "Jeff Kemper"
 A  + @TheDarkPhoenix5  "Christopher Nitzschke (Star..."
 B %+ @gmathewslennon   "Ginny Lennon"
 C  + @marcusramberg    "Marcus Ramberg" (with Unicode R reversed)
 D  + @jshmlr           "Josh Miller"
 E  + @toddberkebile    "Todd Berkebile"
 F  + @noahalexlennon   "Noah Lennon"
 G  + @socalaura        "Laura Brown"
 H  + @Yakpi            "Michael Blanchard"
 I  + @OriginalStartup  "OriginalStartup.com"
 J %+ @brianhafer       "Brian Hafer"
 K %|+@dotmathews       "Dottie Mathews" ## following her back is pending
 L  + @BruceBMathews    "Bruce Basil Mathews"
 M  + @agoldson         "Anthony Goldson"
 N  + @ecard_shark      "Victoria Mathews"
 O  + @chair9           "tom mahoney"
 P  + @MidAtlanticWoman "MidAtlantic Woman"
 Q  + @metacpan         "metacpan"
 R  + @armathews        "Al Mathews"
 S  + @beppu            "John Beppu"
 T^ + @CTDems           "Connecticut Dems"
 U  + @jfluhmann        "Jeremy Fluhmann"
 V  + @mobidextrous     "MobiDextrous"
 W  + @bsgarringer      "Scott Garringer"
 X  + @Scrumpt_ChickN   "Scrumptious_Chick'N"
 Y  + @Strangedayz26    "Joshua Z"                         ### n0t:saying I have 37 fol0rz but Y here would only account for 35 so not sure about other 2?;
3q  Following: ('^' caret=authentic8d_blue_check-mark_user, '%' percent=locked_account, '-' dash=only_following__me_, '+' plus=_me__also_following_them_back)
 0^ - @akidearest       "Spoopydearest"
 1^ - @TheAn1meMan      "Joey"
 2  - @JustinMoen       "Justin Moon"
 3  - @philmyth         "Phil Myth"
 4^ - @joerogan         "Joe Rogan"
 5  - @TheStoicEmperor  "The Stoic Emperor"
 6  - @RoamingMil       "Lauren Chen"
 7  - @Sugar_Tits_Bear  "SugarTits"
 8  - @Undoomed         "Undoomed"
 9  - @thunderf00t      "thunderf00t"
 A  - @logicked         "Logicked"
 B  - @DarkMatter2525   "DarkMatter2525"
 C  - @ShaneLegg        "Shane Legg"
 D^ - @TensorFlow       "TensorFlow"
 E  - @DeepMindAI       "DeepMind"
 F^ - @demishassabis    "Demis Hassabis"
 G^ - @nntaleb          "Nassim Nicholas Taleb"
 H^ - @bariweiss        "Bari Weiss"
 I  - @Shann_Q0         "Shannon Q"
 J  - @CosmologicalYT   "Non-Player Cosmo"
 K  - @gm_skeptic       "GM Skeptic"
 L  - @HumanProgress    "HumanProgress.org"
 M  - @HdxAcademy       "Heterodox Academy"
 N^ - @jonkay           "Jonathan Kay"
 O^ - @DrDebraSoh       "Dr. Debra W Soh"
 P  - @HeatherEHeying   "Heather E Heying"
 Q^ - @EricRWeinstein   "Eric Weinstein"
 R^ - @BretWeinstein    "Bret Weinstein"
 S^ - @JonHaidt         "Jonathan Haidt"
 T  - @Hbomberguy       "Halloween Nickname Bomb..."
 U  - @ContraPoints     "Natalie Wynn"
 V  - @jnthnwrthngtn    "Jonathan Worthington"
 W  - @shadowcat_mst    "SadCowHat mst"
 X  - @kraih            "Sebastian Riedel"
 Y  - @szabgab          "Gabor Szabo" (with foreign accents over first a && last o)
 Z  - @taustation       "Tau Station"
 a  - @QuilletteM       "Quillette"
 b^ - @clairlemon       "Claire Lehmann"
 c^ - @CathyYoung63     "Cathy Young"
 d^ - @OzzyManReviews   "Ozzy Man Reviews"
 e^ - @AMDNews          "AMD News"
 f  - @HoneyBadgerBite  "Honey Badger Radio"
 g  - @Gynocentrism     "Peter Wright gab.ai/Pete..."
 h  - @trgolden         "Tom Golden"
 i  - @JaniceFiamengo   "Janice Fiamengo"
 j  - @erin_pizzey      "Erin Pizzey"
 k  - @redpillmovie     "The Red Pill (movie)"
 l^ - @Cassie_Jaye      "Cassie Jaye"
 m^ - @Tesla            "Tesla"
 n^ - @SpaceX           "SpaceX"
 o^ - @NASA             "NASA"
 p^ - @ProfBrianCox     "Brian Cox"
 q^ - @blatchkiki       "christie blatchford"
 r^ - @MaajidNawaz      "Maajid - (Majid) [ma:d3Id]..." (with weird Unicode)
 s^ - @Ayaan            "Ayaan Hirsi Ali"
 t  - @wadethewiseman   "Wade Wiseman"
 u  - @RationalityRule  "Rationality Rules"
 v^ - @ESYudkowsky      "Eliezer Yudkowsky"
 w  - @Stee_eeve        "NPC_Soren" (with double-dot umlaut? over o)
 x  - @carsieblanton    "Carsie Blanton"
 y^ - @benshapiro       "Ben Shapiro"
 z^ - @RubinReport      "Dave Rubin"
 .^ - @ThatChrisRyan    "Christopher Ryan"
 _  - @askdrstephanie   "Dr.Stephanie Mihalas"
10^ - @JamesADamore     "James Damore"
11  - @JBPetersonQuote  "Jordan Peterson Quotes"
12  - @Jesus_Teaches_   "Jesus Teaches"
13  - @NewWorldHominin  "Lindsay Shepherd"
14  - @nayafia          "Nadia Eghbal"
15^ - @seanmcarroll     "Sean Carroll"
16  - @bgreene          "Brian Greene"
17^ - @rebeccawatson    "Rebecca Watson"
18  - @SkepticsGuide    "SkepticsGuide | skeptic-ing ..."
19^ - @LKrauss1         "Lawrence M. Krauss"
1A^ - @stephenfry       "Stephen Fry"
1B^ - @rickygervais     "Ricky Gervais"
1C^ - @michaelshermer   "Michael Shermer"
1D^ - @danieldennett    "Daniel Dennett"
1E^ - @sapinker         "Steven Pinker"
1F^ - @RichardDawkins   "Richard Dawkins"
1G^ - @SamHarrisOrg     "Sam Harris"
1H^ - @CHSommers        "Christina Sommers"
1I^ - @jordanbpeterson  "Jordan B Peterson"
1J  - @IrateBear        "Irate Scare"
1K  - @MissMisaRants    "Miss Undead Misa"
1L^ - @yegg             "Gabriel Weinberg"
1M  - @duckduckhack     "DuckDuckHack"
1N^ - @DuckDuckGo       "DuckDuckGo"
1O  - @IamPaigeJ        "Paige"
1P  - @SarahTheHaider   "Sarah Haider"
1Q  - @shoe0nhead       "shoe"
1R  - @ArmouredSkeptic  "Skeptic"
1S  - @CounterArguing   "Counter Arguments"
1T  - @ObsidiaMedia     "Obsidia"
1U  - @ScreepsWorld     "ScreepsWorld"
1V  - @ScreepsGame      "Screeps"
1W^ - @Google           "Google"
1X  - @PerlConferences  "Perl Conferences"
1Y  - @wdanlennon       "Dan Lennon"
1Z %- @emma_lemon       "Emma Lennon"
1a^ - @Snowden          "Edward Snowden"
1b^ - @HillaryClinton   "Hillary Clinton"
1c  - @radiofreesrini   "srini kumar"
1d^ - @POTUS44          "President Obama"
1e^ - @POTUS            "President Trump"
1f^ - @LastWeekTonight  "Last Week Tonight"
1g^ - @TheDailyShow     "The Daily Show"
1h^ - @alfranken        "Al Franken"
1i^ - @SenWarren        "Elizabeth Warren"
1j^ - @BernieSanders    "Bernie Sanders"
1k^ - @SenSanders       "Bernie Sanders"
1l  - @clemantine1      "Clemantine"
1m^ - @irin             "Irin Carmon"
1n  - @romerikk         "Romerik Rousseau"
1o %- @AaronMaxA        "Aaron Max Abramowicz"
1p  - @rockoff          "Kevin R"
1q  - @Richsaunders     "Richard Saunders"
1r  - @PerlRick         "Rick Deller"
1s  - @PerlTricks       "David Farrell"
1t  - @PerlWeekly       "Perl Weekly"
1u^ - @tmbg             "They Might Be Giants"
1v  - @perlbuzz         "perlbuzz"
1w  - @Jonathan_Blow    "Jonathan Blow"
1x  - @chromatic_x      "."
1y^ - @perlfoundation   "The Perl Foundation"
1z  - @rjbs             "Ricardo SIGNES"
1.  - @TimToady         "Larry Wall"
1_  - @DanFloydPlus     "Daniel Floyd"
20  - @ExtraCreditz     "Extra Credits"
21  - @JamesPortnow     "James Portnow"
22^ - @NateSilver538    "Nate Silver"
23^ - @Medium           "Medium"
24  - @tommensch        "Thomas Mensch"
25  - @verytragic       "Ben Cureton"
26^ - @StephenAtHome    "Stephen Colbert"
27  - @ldgabbay         "Lynn Gabbay"
28  - @shanestudebaker  "Shane Studebaker"
29  - @brettskib        "Brett Blumstein"
2A  - @KarenIvyRiggers  "Karen Riggers"
2B  - @billygail        "Gail Lennon"
2C  - @akotev           "Amichai Kotev"
2D  - @kmwkyle          "Who Dis"
2E  - @youvegotitnow    "Sina Aryeh"
2F  - @thefirstmanaism  "Megan Mathews"
2G  - @wdlennon         "Dan Lennon"
2H  - @sganem1          "Steve Ganem"
2I  - @BalfordBe        "Be Alford"
2J^ - @CapcomFighters   "Capcom Fighters"
2K  - @SethBB           "Seth Brown"
2L  - @henryjlennon     "Henry Lennon"
2M  - @PerlSawyer       "Sawyer X"
2N  - @SRKRanking       "SRK Stats"
2O  - @derek_omni       "Derek Daniels"
2P  - @jchensor         "James Chen"
2Q  - @RealChrisLi      "Chris Li"
2R  - @shoryukendotcom  "Shoryuken.com"
2S^ - @EVO              "EVO"
2T^ - @MrWiz            "Joey Cuellar"
2U  - @ProtomCannon     "Tom Cannon"
2V  - @Pond3r           "Tony Cannon"
2W  - @AllisonPratt     "Allison Pratt"
2X  - @Pr1meCandidate   "PrimeCandidateInc"
2Y %- @vroomtim         "Tim Vroom"
2Z^ - @maddow           "Rachel Maddow MSNBC"
2a^ - @alyankovic       "Al Yankovic"
2b^ - @iamjohnoliver    "John Oliver"
2c^ - @timoreilly       "Tim O'Reilly"
2d^ - @Pontifex         "Pope Francis"
2e  - @SirlinGames      "Sirlin Games"
2f  - @topnewsbitcoin   "Bitcoin News & Views"
2g^ - @BarackObama      "Barack Obama"
2h  - @SashaStrauss     "Sasha Strauss"
2i  - @OvidPerl         'Curtis "Ovid" Poe'
2j^ - @BillNye          "Bill Nye"
2k^ - @spolsky          "Joel Spolsky"
2l^ - @neiltyson        "Neil deGrasse Tyson"
2m  - @Sirlin           "David Sirlin"
2n  - @Torreyology      "Torrey Stud"
2o^ - @ID_AA_Carmack    "John Carmack"
2p  - @lionlotek        "Thomas Grove" (with accent over e)
2q  - @lars_bakken      "Lars Bakken"
2r  - @jasonenfuego     "Jason Gosnell"
2s  - @foz              "Jeremy Seitz"
2t  - @neilbowers       "Neil Bowers"
2u^ - @codinghorror     "Jeff Atwood"
2v  - @dj80bugg         "Eighty Bugg"
2w^ - @sethkillian      "Seth Killian"
2x^ - @TheEllenShow     "Ellen DeGeneres"
2y^ - @github           "GitHub"
2z  - @houseabsolute    "Dave Rolsky"
2.  - @kristoffersing   "Kristoffer Singleton"
2_  - @bjbig            "BJ Bigley"
30  - @aradhanaa        "Nina E. Woodard"
31  - @scrottie         "Scott Walters"
32^ - @BWilliams        "Brian Williams"
33  - @paulb1776        "Paul Blumstein"
34  - @MidCityFace      "Michael Leonard"
35^ - @larryellison     "Larry Ellison"
36  - @kellyjobarnes    "Kelly Boeldt"
37  - @jacob77          "Jacob Conrad"
38^ - @andersoncooper   "Anderson Cooper"
39^ - @marissamayer     "marissamayer"
3A  - @coopanimate      "jeff cooperman"
3B  - @ycombinator      "Y Combinator"
3C^ - @GStephanopoulos  "GeorgeStephanopoulos"
3D^ - @PCMag            "PCMag"
3E^ - @elonmusk         "Elon Musk"
3F^ - @arstechnica      "Ars Technica"
3G %- @vulgartooth      "earnest dumbass"
3H^ - @Gizmodo          "Gizmodo"                                ### final 210 here plus 34 bi-directional follows up top yields expected 244 currently;
FcBk: # 2du:process xportd zip of all d8a as JSON from d8:IAJ to valid8 that I can more confidently migr8 away from FcBk platform && preserve contax at least;
