What else is new... (Score:5, Funny) by mschaffer (97223) Alter Relationship on Thursday May 28, 2015 @12:07AM (#49787153)

So what else is new? Most "Global Business Leaders" don't know much about anything else, yet some succeed due to blind luck and sheer force of money.

A man in a hot air balloon realised he was lost. He reduced altitude and spotted a woman below.
He descended a bit more and shouted, "Excuse me, can you help me? I promised a friend I would meet him an hour ago, but I don't know where I am."
The woman below replied, "You're in a hot air balloon hovering approximately 30 feet above the ground. You're between 40 and 41 degrees north latitude and
 between 59 and 60 degrees west longitude."
"You must be an engineer," said the balloonist.
"I am," replied the woman, "How did you know?"
 "Well," answered the balloonist, "everything you told me is technically correct, but I've no idea what to make of your information, and the fact is I'm still
 lost. Frankly, you've not been much help at all. If anything, you've delayed my trip."
The woman below responded, "You must be in Management."
"I am," replied the balloonist, "but how did you know?"
"Well," said the woman, "you don't know where you are or where you're going. You have risen to where you are due to a large quantity of hot air. You made a
 promise, which you've no idea how to keep, and you expect people beneath you to solve your problems. The fact is you are in exactly the same position you
 were in before we met, but now, somehow, it's my fault."
