#!/usr/bin/perl
# IC8L823c:U23c by GG 2 turn U2b Xl8 transcripts 2 3 columns (52x3=156chars);
# xscrpt-7IxXQytAVhc.utf
# xscrpt-KguZY7zq-ww.utf
# xscrpt-nQRzxEobWco.utf
# xscrpt-qDuVkbW87F0.utf
# xscrpt-vs4nh7fPZp8.utf
use strict;use warnings;use utf8;use v5.10;use Path::Tiny;my $d8VS='ICCLJOIN';
for my $sfnm (<"xscr*.*">){my $sfil=path($sfnm)->slurp_utf8(); my $sfno=$sfnm; # build-up ScriptIn3Columns
  if($sfno=~ s/(xscr)i?p?t?(-.*)\.(utf|txt|log|x?scr?p?t?|sub|cc)$/3c$1$2-$d8VS.$3/i){my $si3c='';say "Gener8ing $sfno from $sfnm...";
    my @slnz=split(/\n/,$sfil);for(0..$#slnz){$slnz[$_]=sprintf("%-52s",$slnz[$_]);}  my $thrd=int(@slnz / 3); # should loop to end
    for(0..$thrd ){$si3c.=$slnz[$_].$slnz[$thrd+$_];$si3c.=$slnz[2*$thrd+$_] if((2*$thrd+$_) <= $#slnz);$si3c=~ s/\s*$/\n/;}
    open my $outs,'>',$sfno or die "Can't open  Output Script handle: $!";binmode $outs,':encoding(UTF-8)';print $outs $si3c;
    close   $outs           or die "Can't close Output Script handle: $!";}} # && that should probably about do it?!  =)  ;
