# K8NMCaps:~/dox/2du/ps.ls crE8d by PipStuart <Pip@CPAN.Org> to list a Prioritized Sequence of Prominent word-PairS which Share my initials; $d8VS='K8OMGood';
Philip          Stuart      ;    Platonic     Solid      ;    Powered     Subwoofer ;
Play            St8ion      ;    Perfect      Storm      ;    Philosopher Stone     ;
Perl            Script      ;    Penny        Stocks     ;    Party       Supplies  ;
Power           Supply      ;    Phone        Speaker    ;    People      Suck      ;
Power           Surge       ;    Preferred    Seating    ;    Particle    Smasher   ;
Power           Strip       ;    Pyrotechics  Show       ;    Product     Search    ;
Penis           Shaft       ;    Presidential Seal       ;    Puffy       Snatch    ;
Postal          Service     ;    Pound        Sign       ;    Pound       Sand      ;
Parcel          Service     ;    Poor         Soul       ;    Pulmonary   Specialist;
Pencil          Shavings    ;    Pipe         Smoke      ;    Playback    Speed     ;
Pencil          Sharpener   ;    Penguin      Slide      ;    Post        Script    ;
Pretern8ural    Selection   ;    Prickly      Sens8ion   ;    Pig         Skin      ;
Primordial      Soup        ;    Paper        Shredder   ;    Pittsburgh  Steelers  ;
Progresso       Soup        ;    Pithy        Saying     ;
Public          Storage     ;    Pumpkin      Squash     ;    Pumpkin     Spice     ;
Personal        Savior      ;    Person (1st) Shooter    ;    Pie         Slice     ;
Prayer       && Supplic8ion ;    Playing      Safe       ;    Pickle      Spears    ;
Pepper       && Salt        ;    Peanutbutter Sandwich   ;    Pastrami    Sandwich  ;
Potatos      && Steak       ;    Pasta        Sauce      ;    Porterhouse Steak     ;
Pleasant        Surprise    ;    Plentiful    Supply     ;
Penetr8ing      Stare       ;    Peach        Sorbet     ;
Prison          Sentence    ;    Prison       System     ;
Putrid          Stench      ;    Punch        Strong     ;
Puff         of Smoke       ;    Potent       Stimulant  ;    Pint     of Stout     ;
Piece        of Shit        ;    Personal     Space      ;
Point        of Sale        ;    Personal     Sign8ure   ;    Peace       Sign      ;
Pork            Soda        ;    Planetary    System     ;
Pant          - Suit        ;    Plain     && Simple     ;
Pain          - Staking     ;    Putter    && Sand-wedge ;
Phillips        Screwdriver ;    Peace     && Serenity   ;
Pick-up         Sticks      ;    Poop         Stain      ;    Pay         Stub      ;
Pretty          Stupid      ;    Pressure   - Sensitive  ;    Pro       - Social    ;
Puget           Sound       ;    Pl8        - Shifter    ;    Psycho    - Somatic   ;
Prime           Sequence    ;    Paradigm     Shift      ;
Protein         Sequence    ;    Prodigal     Son        ;
Professional    Software    ;    Process      Snapshot   ;
Prescription    Sunglasses  ;    Purse        Strings    ;
Passion8        Seduction   ;    Powdered     Sugar      ;    Passion8    Sex       ;
Positioning     System      ;    Poached      Salmon     ;    Penetr8ion  Shot      ;
Portable        Stereo      ;    Pop          Star       ;    Power       Series    ;
Pressure        Switch      ;    Porn         Star       ;    Power       Switch    ;
Pancake         Syrup       ;    Perverted    SonOfABitch;
Pointed         Spear       ;    Pounds    of Semen      ;
Pokemon         Sapphire    ;    Panties      Showing    ;
Pocket          Stopwatch   ;    Purple       Skirt      ;
Primitive       Superstition;    Primal       Savage     ;
Pointless       Something?  ;    Paragraph    Summary    ;
