#!/usr/bin/perl
use strict;use warnings;use utf8;use v5.10;use Octology::a8;use Octology::b8;
my $d8VS='LCALAMAR'; # 2du:slurp f0n.ls && gener8 4mz of all b64 area-codez regionally (not Default sorted numerical order), 3-prefixes numerical, 3-suffix+1;
#    setup gNpr0 2tk 64 4-letr werdz && gNR8 ~/.log/prof.ls from pr0.ls 4LoKi;
# LK (){ if [[ $COLUMNS -lt 160               ]]; then # new LoKi StarLord Quill (Quest?) ChristopherNitzchke brother-man (not LiuKang) to show b10 of b64 LK;
#   export lk='lOkI';       b10 $lk|cma|b8clr;ec "$W=${m}l${O}O${k}k${p}I$g as$B b10$w;$z"; # l8r substr/regex out sub-charz && auto y/// or UC($lk) 42 LK;
#   export LK='LoKi';en ' ';b10 $LK|cma|b8clr;ec "$W=${M}L${o}o${K}K${P}i$G as$B b10$W;$z"; fi }
# alias lk='LK';         # [pip@OniLC9L8jKm~]lk
# 12,422,034=lOkI as b10;  [pip@OniLC9~]en "also LoKi stuf 4 4-letr word nvrt case 2 half whol pair with S($letr) etc."
#  5,711,148=LoKi as b10;  [pip@OniLC9L8jLw~]en '(920)636-6271'
# (920)636-6271            [pip@OniLC9L8l5G~]b64 920
#  EO                      [pip@OniLC9L8lDi~]b64 636
#      9y                  [pip@OniLC9L8lIH~]b64 6271
#         -1X_             [pip@OniLC9L8lMV~]b10 EO
# (920)                    [pip@OniLC9L8lUV~]b10 9y
#      636                 [pip@OniLC9L8lXs~]b10 1X_
#         -6271            [pip@OniLC9L8lbj~]en '(920)637-8634'
# (920)637-8634            [pip@OniLC9L8mCH~]b64 637
#      9z                  [pip@OniLC9L8mLE~]b64 8634

#         -26w             [pip@OniLC9L8mc5~]en "(EO)9y,z-1X_,26w;"
# (EO)9y,z-1X_,26w;
