#!/usr/bin/perl
# IC1:GG by GG;2du:fix -e && -v wi -1 || -2 stopng Dflt hIlI,fix pQC:MzC ordr;
# 2du:enable -e to Dflt insrt Blue$ in every empty 80th colm 4 multi-wId lInz,
#   try2 Get RegGent99@PM && othr Xmplz,Xtract out this GG code into a8 libz?,
#   add -d8= optnz for navig8ing around .$Year./.$d8.GG. fIlz2link customIzdz,
#   add -random flag(or rEaloc8 -s like shufl),add -n just allraw plaiN$z out,
#   upd8 all "pLAINZ" rFrNcz2specialNew "Normal" S(':N'||'^') mABas$Nnstdof$J,
#   upd8 typz && clrz paramz so that any DfInd types canBordrd wi customcolrz,
#   rEduSubjz/^(d8[=:])?(J99[^=:;]*[=:;]|$)?(typ|[bs]gr|f0n|muz)?([=:].*)?$/i,
#   add mor granUlR typz like sepR8 a''postro vs Q"",q??uestn,As**tar,p()aren,
#   alow lArz 2B nSted wi custmcolrz4depth&&nOdz,DfIn typ4just smOx&&Br colrz,
#   proly add typ4 all b64chrz colrdbypal8SKpz,Punctu8ntyp4goodcolrzof nonb64,
#   combIn all bSt typz,ordrz,nStngz,etc2Bcom advncdDfltpwr opt4fInl.*/.*.GG.,
#   prIoritIz&&golfcorecOd dn2clEnSt79x49 4m@,upd8 -Helptxt &&optnflaghandlng,
#   mAB du GetOpt:Long,accept pIping thru nstdofDflt slurp,add %ENV cfg4mngmt,
#   forkoff2new tRget sIzes:79x19&&159x49 2fOcusfUturfE8urz4,add bkgr&&SGRsgr,
#   add optz4 FDALbdal pal8 lArz2alsO cntrl DarkAvrgLite plAnz of b64 colrkyz,
#   spawnSDLnew .png gNr8or wich tAkz f0nt&&pal8 optz2,rsrch intrst8 mailawz2,
#   cNtralIz&&Unify allDflt custmcolr cfgzsOcOdEZ2ed&&goodoptzcanset grupdc@z,
#   rsrch bSt PerlpAstbinz4snipzof all .$d8.GG. fIlz&&`GG-$d8`or opt2runcolrz,
#   polish fInSt d8a wi cOd&&plan bSt rollout2GGz who cud bSt b8a-tSt && Njoy,
#   branch off newGGPMlz in2sepR8d or nSted kpc DBz by 4CablUsag c@egorEz4GGz,
#   cnsidr bSt wA2specialKs alow '^' 4$z so th@ actual S('z') sepR8d&&!s/z/^/,
#   cnsidr bSt wAz2rEstrict BhAv4 cnsistNt rEsltz4all d8a UknOUcare4,plan mor,
#   mk cfg(mABjustincOd)4smRt autOmapng certAncustmcOd+optz2Dflt pRticUlR d8a,
#   mk sepR8Utl4mergng newd8afIlz byd8,auth,trust,sIzlimtz,conflixreso4mz,etc,
#   proly bild hIerRkE of typmapz byabovzAgN2grO nAmspAcz4difUzrz2DfIn OwnGGz,
#   considr:GreenGo,Yellow chess,BlueBladeBatlz,&&lastOrange bStEmAld cRdgAmz,
#   mABTexasHoldEm ifsome unbIasdEmAlprocScud mED8shflz4prIv8hole&&publicRdz?,
#   proly cOordin8ing any4m ofcRd or othrturnbAsdgmzOvrprIv8GGEmAlzfitzthEmwL.
#   Beyond just buying cartons of Cheyenne && 25-packs of Black&&Mild,it would
# also probably be good to order a box of Graph-Paper notebooks&&8GB SDs2send;
use strict ;use v5.10;use Octology::a8;my $VERSION='0.000'; #GuyGoowaysProMaYO
use warnings;use utf8;use Octology::d8;my $d8VS='IC5LGuyG'; #upd8YourOwnBoyggz
use      Path::Tiny  ; my $J99f='.J99.GG.'    ;my @jclz=(); #J CodedColorListz
my $j99f=path($J99f)->slurp_utf8();my %czcn=();my %j94c=(); #basic2019formatCz
open my $out8,'>&',STDOUT or die "Can't open  duplic8 STDOUT handle: $!"; #J99
binmode $out8,':encoding(UTF-8)'  ;my $N=$0;$N=~ s/^.*\///; #setupUTF8outpName
my $jcpo='';my $hflg=0;my $aflg= 0;my $eflg=1; #-optn FLaGz #J ColorParseOptnz
my $fflg= 0;my $sflg=0;my $vflg= 1;my $xflg=1;if(@ARGV){$jcpo=join(' ',@ARGV);
   $aflg^=1 if($jcpo=~ s/-+a//i);$fflg^=1 if($jcpo=~s/-+[f1]//i); #-Digit;f1st
   $eflg^=1 if($jcpo=~ s/-+e//i);$sflg^=1 if($jcpo=~s/-+[s2]//i); #-Endl$;s2nd
   $vflg^=1 if($jcpo=~ s/-+v//i);$xflg^=1 if($jcpo=~s/-+x//i); #-Vers;Xtrasend
   $hflg^=1 if($jcpo=~ s/-+h//i);} my $edol= S('Bb') .'$'. $z; #-HelpFLaG;$end
my($A,$D,$J,$S);if(!defined($jcpo)||!length($jcpo)){$jcpo='9'  if($aflg     );
   $jcpo='pQC:CMz' if($jcpo!~/\S/);}     if($hflg ){      print   $out8 "$z ".
"-h - print this Helptext,  -v - Version at end,  -1 -f - print Fir1st column;
 -e - Endline blue dollar,  -x - Xtra vline end,  -2 -s - print Sec2nd column;
 -a - ApplyAll Attributes;  ";$jcpo='';$xflg=0;} # skip file outp&&jmpdn2-Vers
while($jcpo=~s/^([^;]+)(;|$)//){my $j94m=$1;     ##my @jpto=(split(//,'pQC'));
  my %jptm = ('p'=>'pLAINZ','Q'=>'Quotem','C'=>'CommentC'); #J ParseTypemapngz
  if($j94m =~ /^(([^:]+?):)?([^;]+)(;|$)/){my $typz=$2;my $clrz=$3;  #parse4m@
    $clrz='' if (!defined($clrz));            $typz='' if(!defined($typz)); ##
    for my $colr(split(//,$clrz)){unshift(@jclz,$colr);}#loop unsh nstdof push
    for my $colr(@jclz){$czcn{$colr}=S($colr) if($colr=~ /[A-Z]/ );} #loadclrz
    for my $type(split(//,$typz)){if($type=~/[pQC]/){push(@jclz,'r')if !@jclz;
        push(@jclz,shift(@jclz));$j94c{$type}=$jclz[-1];}}  # brokencyclez4now
    $eflg^=1 if($fflg || $sflg);$eflg^=1 if($clrz=~ /GG/);  # toglEndflagvaluz
    for my $line(split(/\n/,$j99f)){     if(defined($line)  && length($line)){
      if(length($line) > 79){if($fflg){$line=substr($line,0,79);}elsif($sflg){
         substr($line,0, 79,'');$line=~ s/^\s//;}} #mABOnlychop80spc if -eflg?
        if($clrz=~/G/){$J=S($j94c{'p'}='d');if($clrz=~/GG/){                 #
             my $j= $J;$j=S($j94c{'p'}='K'); # setup nested dupd jJ 4 GG optnz
        $line=~s/([I-J])([369C]|Sep[^0-9.]*)(\d?[0-9A-V])/$R$1$o$2$Y$3$J/g;  #
           $line=~ s/(20?)(\??)(1[89])/$R$1$o$2$R$3$J/g; # use two2outrJjz4d8z
         for my $j9ky(split(//,'zMC')){$j=$S=S($j94c{'p'}) if($j9ky=~ /z/);  #
           $line=~ s/^([^\e])/$j$1/;if($j9ky=~ /^[zMC]/){$S=S($j9ky      );  #
           $line=~ s/($j9ky [a-y]*)/$S$1$j/gx;}}} #origChrCls[a-yABD-FH-LNP-X]
         for my $j9ky(sort(keys(%czcn)),split(//,'GYOB')){$J=$z;$S=S('Rr');  #
           if(exists($j94c{'p'}) && $j94c{'p'}=~ /[^z]/){$J=S($j94c{ 'p'});} #
           $S=$czcn{$j9ky} if exists($czcn{$j9ky});$line=~s/^([^\e])/$J$1/;  #
           if($j9ky=~ /([CMGYOB])/){$S=S($1);$S=S('o') if($j9ky=~/O/)     ;} #
           $line=~ s/($j9ky [a-z]*)/$S$1$J/gx;}} # above: crit6, no redefinez!
        else{if(exists($j94c{p})){$J=S($j94c{p});$J=$z if($j94c{p}=~  /z/);  #
           $line=~ s/(^[^\#])/$J$1/;} #$line=~ s/(^|\s)([^'"\#\e\t ])/$1$J$2/;
  if(exists($j94c{Q})){$S=S($j94c{Q});$line=~ s/('[^']*'|"[^"]*")/$S$1$J/g;} #
  if(exists($j94c{C})){$S=S($j94c{C});$line=~ s/((^|\s) \#(.*)  )/$S$1$J/x;  #
  if(defined($3)){$A=$D=$3;$D=~s/\e\[[0-9;]*m//g;$line=~s/(\#)\Q$A\E/$1$D/;}}} my $park='';
      $line.=$edol if $eflg;say $out8 $line;}}}} $J=$z;$J.="\n"      if $xflg; if($aflg){for my $ggd8 (qw(J99 J33 IC2 J4K)){for my $parm ('', qw(9 G GG)){
      $park ='K' if($ggd8=~ /4K/);print $out8 `perl .GG.$ggd8. $parm$park`;}}} # mAB this will run thru most optnz 4 -AllArrayedAttributeAccessesActiv8d?;
print $out8 "$z$G$N $Y-$B v$C$VERSION ".d8c($d8VS)."$W;$J"           if $vflg;
close $out8 or die "Can't close duplic8 STDOUT handle: $!"; # "GoodGameGent"!;
